### PR TITLE
remove broken links

### PR DESCRIPTION
**Pull request by pyrog**

### CODE REVIEW

**Comment by wetneb** [comment]
I am a bit on the fence about this, perhaps it would be better to point to archived versions of these pages, if they exist?

**Comment by pyrog** [comment]
- For VIB-BITS, post talking about there extensions still exist on their site 😄, but no code 😞
- For BioVel, their wiki is dead, but their repo is still there 😄 
- For CKAN Extension Storage  v0.1 (alpha), the site is dead and it was an alpha version released 2014 for Google Refine (also dead 😉)<br/>Good news, the CKAN Extension Storage for OpenRefine 2.6-beta1 and CKANv2.2+ is still alive 😃

So that's why is deleted some, and remove the broken link for other.
If somebody know an archive, it will fine.

**Comment by jgiaccai** [comment]
I was just in the process of submitting a request for removing some of the same links.  I also can't find any record of the two VIB-Bits extensions on their website.

**Comment by wetneb** [comment]
Let's ping @tfmorris about this since he is interested in preservation of extensions.

**Comment by ostephens** [comment]
As @allanaaa has now got a PR in motion for a more substantial set of changes to the list of extensions I suggest we offer thanks and apologies to @pyrog and close this PR @wetneb ?

**Comment by ostephens** [comment]
Superseded by #82

**Pull request closed without merging**
